# Generated by Django 2.2.7 on 2019-12-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191115_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
